{
 "title": "Admin Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Platform Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "alias": "Total Users",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "type.keyword=total_users_registered",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Signups",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "alias": "Signups",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "settings": { "script": "1" }, "type": "sum" }
     ],
     "query": "type.keyword=signup",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "User logins",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "alias": "Successful",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "settings": { "script": "1" }, "type": "sum" }
     ],
     "query": "type.keyword=user_login AND\nisLoginSuccessful:true",
     "timeField": "timestamp"
    },
    {
     "alias": "Failed",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "settings": { "script": "1" }, "type": "sum" }
     ],
     "query": "type.keyword=user_login AND\nisLoginSuccessful:false",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Contest Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Total Contests",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "count", "id": "1", "type": "sum" }
     ],
     "query": "type.keyword=total_contests",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Ongoing & Completed Contests",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Ongoing",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "count", "id": "1", "type": "sum" }
     ],
     "query": "type.keyword=ongoing_contests",
     "timeField": "timestamp"
    },
    {
     "alias": "Completed",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "count", "id": "1", "type": "sum" }
     ],
     "query": "type.keyword=completed_contests",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Contest Details",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "type.keyword=contest_details",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "System errors & Warnings",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "type.keyword=system_errors",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Security Incidents",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "type.keyword=security_incidents",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}