{
 "title": "Contest Admin Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "contest_name",
    "label": "Contest Name",
    "query": "{\"find\":\"terms\",\"field\":\"contest.name.keyword\"}"
   }
  ]
 },
 "panels": [
  { "title": "Contest Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Leaderboard",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "type.keyword=contest_leaderboard AND\ncontest.name.keyword:$contest_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Difficulty Distribution of Challenges",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Easy",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "type.keyword=challenge_details AND\ncontest.name.keyword:$contest_name AND\ndifficulty.keyword=easy",
     "timeField": "timestamp"
    },
    {
     "alias": "Medium",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "type.keyword=challenge_details AND\ncontest.name.keyword:$contest_name AND\ndifficulty.keyword=medium",
     "timeField": "timestamp"
    },
    {
     "alias": "Hard",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "type.keyword=challenge_details AND\ncontest.name.keyword:$contest_name AND\ndifficulty.keyword=hard",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Category Distribution of Challenges",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Easy",
     "bucketAggs": [
      {
       "field": "challenge.category.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "type.keyword=challenge_details AND\ncontest.name.keyword:$contest_name AND\nchallenge.difficulty.keyword=easy",
     "timeField": "timestamp"
    },
    {
     "alias": "Medium",
     "bucketAggs": [
      {
       "field": "challenge.category.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "type.keyword=challenge_details AND\ncontest.name.keyword:$contest_name AND\nchallenge.difficulty.keyword=medium",
     "timeField": "timestamp"
    },
    {
     "alias": "Hard",
     "bucketAggs": [
      {
       "field": "challenge.category.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "type.keyword=challenge_details AND\ncontest.name.keyword:$contest_name AND\nchallenge.difficulty.keyword=hard",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Total Participants",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "alias": "Participants",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "count", "id": "1", "type": "sum" }
     ],
     "query": "type.keyword=total_participants_registered AND\ncontest.name.keyword:$contest_name",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}